apiVersion: apps/v1
kind: Deployment
metadata:
  name: enter
  labels:
    app: enter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: enter
  template:
    metadata:
      labels:
        app: enter
    spec:
      containers:
        - name: enter
          image: "username/enter:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
